# Generated by Django 4.2.20 on 2025-11-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option_index', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.chapter')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('max_questions', models.IntegerField(default=15)),
                ('current_ability', models.IntegerField(default=0)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(blank=True, null=True)),
                ('overall_attention_ratio', models.FloatField(blank=True, null=True)),
                ('overall_avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('webgazer_enabled', models.BooleanField(default=True)),
                ('calibration_quality', models.FloatField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_sessions', to='quizzes.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_index', models.IntegerField()),
                ('difficulty_at_attempt', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('ability_before', models.IntegerField()),
                ('ability_after', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('response_time_ms', models.IntegerField()),
                ('selected_option_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('was_skipped', models.BooleanField(default=False)),
                ('attention_ratio', models.FloatField(blank=True, null=True)),
                ('off_screen_ratio', models.FloatField(blank=True, null=True)),
                ('off_screen_duration_ms', models.IntegerField(blank=True, null=True)),
                ('num_gaze_samples', models.IntegerField(default=0)),
                ('num_on_task_samples', models.IntegerField(default=0)),
                ('num_off_task_samples', models.IntegerField(default=0)),
                ('option_changes', models.IntegerField(default=0)),
                ('flagged_low_attention', models.BooleanField(default=False)),
                ('raw_attention_trace', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quizzes.question')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quizsession')),
            ],
            options={
                'db_table': 'question_attempts',
                'ordering': ['question_index'],
                'unique_together': {('quiz_session', 'question_index')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'difficulty', 'is_active'], name='questions_chapter_22c7bf_idx'),
        ),
    ]
